name: CI

on:
  push:
    branches:
      - main
    paths:
      - include/**
      - src/**
      - test/**
      - .github/workflows/ci.yml

jobs:

  unittest:
    name: Unit test
    runs-on: ubuntu-latest
    container:
      image: naokihori/alpine-cunit:1.0
      volumes:
        - :/home
      options: --rm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          repository: 'NaokiHori/SimpleNpyIO'
          ref: 'main'
      - name: Prepare place to store artifacts
        run: mkdir artifacts
      - name: Build and Run Tests
        run: |
          cd test/unit
          make clean
          make
          for f in *.out;
          do
            ./$f
          done
      - name: Convert XML to JSON
        id: create-json
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test/unit/*.xml
          json_file: artifacts/unittest.json
          job_summary: false
          check_run_annotations: "none"
      - name: Parse JSON and create badge
        run: |
          # extract numbers from JSON
          tests=${{fromJSON(steps.create-json.outputs.json).stats.tests}}
          tests_succ=${{fromJSON(steps.create-json.outputs.json).stats.tests_succ}}
          tests_skip=${{fromJSON(steps.create-json.outputs.json).stats.tests_skip}}
          tests_fail=${{fromJSON(steps.create-json.outputs.json).stats.tests_fail}}
          tests_error=${{fromJSON(steps.create-json.outputs.json).stats.tests_error}}
          # label
          label="UnitTest"
          # badge color, red if error, otherwise green
          if [ $(($tests_skip+$tests_fail+$tests_error)) -ne 0 ]; then
            color="red"
          else
            color="green"
          fi
          # message contains results
          message="${tests}tests,${tests_succ}success"
          # request badge
          link=https://img.shields.io/badge/$label-$message-$color.svg
          wget --output-document=artifacts/badge_unittest.svg "$link"
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: unittest
          path: artifacts

  integrationtest:
    name: Integration test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          repository: 'NaokiHori/SimpleNpyIO'
          ref: 'main'
      - name: Prepare place to store artifacts
        run: mkdir artifacts
      - name: Build Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install Libraries
        run: pip install numpy pytest
      - name: Build and Run Tests
        run: |
          # checkout directory
          cd test/integration
          # build C library
          make clean
          make all
          # create sample npy files using Numpy
          python3 create.py
          # load sample npy files, interpret them,
          #   and output them again to the other files
          for f in test*.out; do
            ./$f
          done
          # compare original and dumped arrays
          pytest --junit-xml=integrationtest.xml compare.py
      - name: Convert XML to JSON
        id: create-json
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test/integration/*.xml
          json_file: artifacts/integrationtest.json
          job_summary: false
          check_run_annotations: "none"
      - name: Parse JSON and create badge
        run: |
          # extract numbers from JSON
          # https://docs.github.com/ja/actions/learn-github-actions/expressions#fromjson
          tests=${{fromJSON(steps.create-json.outputs.json).stats.tests}}
          tests_succ=${{fromJSON(steps.create-json.outputs.json).stats.tests_succ}}
          tests_skip=${{fromJSON(steps.create-json.outputs.json).stats.tests_skip}}
          tests_fail=${{fromJSON(steps.create-json.outputs.json).stats.tests_fail}}
          tests_error=${{fromJSON(steps.create-json.outputs.json).stats.tests_error}}
          # label
          label="IntegrationTest"
          # badge color, red if error, otherwise green
          if [ $(($tests_skip+$tests_fail+$tests_error)) -ne 0 ]; then
            color="red"
          else
            color="green"
          fi
          # message contains results
          message="${tests}tests,${tests_succ}success"
          # request badge
          link=https://img.shields.io/badge/$label-$message-$color.svg
          wget --output-document=artifacts/badge_integrationtest.svg "$link"
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: integrationtest
          path: artifacts

  memoryleakcheck:
    name: Memory leak check
    runs-on: ubuntu-latest
    container:
      image: naokihori/alpine-valgrind:1.0
      volumes:
        - :/home
      options: --rm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          repository: 'NaokiHori/SimpleNpyIO'
          ref: 'main'
      - name: Prepare place to store artifacts
        run: mkdir artifacts
      - name: Run tests and create badge
        run: |
          make clean
          make
          # badge label
          label="MemoryLeakCheck"
          # badge color and message
          if valgrind \
            --leak-check=full \
            --error-exitcode=1 \
            --xml=yes \
            --xml-file=artifacts/valgrind.xml \
            ./a.out; then
            color="green"
            message="passing"
          else
            color="red"
            message="failed"
          fi
          # request badge
          link=https://img.shields.io/badge/$label-$message-$color.svg
          wget --output-document=artifacts/badge_memoryleakcheck.svg "$link"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: memoryleakcheck
          path: artifacts

  publish:
    name: Publish CI results
    runs-on: ubuntu-latest
    needs: [unittest, integrationtest, memoryleakcheck]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          repository: 'NaokiHori/SimpleNpyIO'
          ref: 'main'
      # import artifacts generated in the previous steps
      - name: Download artifacts (unittest)
        uses: actions/download-artifact@v3
        with:
          name: unittest
      - name: Download artifacts (integrationtest)
        uses: actions/download-artifact@v3
        with:
          name: integrationtest
      - name: Download artifacts (memoryleakcheck)
        uses: actions/download-artifact@v3
        with:
          name: memoryleakcheck
      # collect all artifacts (test logs and badges) which will be officially published
      - name: Collect artifacts
        run: |
          sudo mkdir -p .github/workflows/artifacts/
          sudo /bin/mv *.xml  .github/workflows/artifacts/
          sudo /bin/mv *.json .github/workflows/artifacts/
          sudo /bin/mv *.svg  .github/workflows/artifacts/
      # start tracking artifacts
      - name: Track artifacts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git switch -c artifacts
          git add .github/workflows/artifacts/*
          git commit -m "Update CI artifacts" -a || true
      # push artifacts to "artifacts" branch
      - name: Push artifacts
        uses: ad-m/github-push-action@master
        with:
          branch: artifacts
          directory: "."
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          force: true

