name: CI

on:
  push:
    branches:
      - main
    paths:
      - include/**
      - src/**
      - test/**
      - .github/workflows/ci.yml
  workflow_dispatch:

jobs:
  test:
    name: Create NPY files in C and load from Python, vice versa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Libraries
        run: |
          python -m pip install --upgrade pip
          pip install numpy
      - name: Build and Run Tests
        working-directory: test
        run: |
          make clean
          make all
          python3 runner.py

  memory-leak-check:
    name: Check memory leak
    runs-on: ubuntu-latest
    container:
      image: naokihori/alpine-valgrind:1.0
      volumes:
        - :/home
      options: --rm
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Run Valgrind
        run: |
          make clean
          make all
          valgrind --leak-check=full --error-exitcode=1 ./a.out
