name: Deploy-Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/source
      - .github/workflows/pages.yml
  workflow_dispatch:

jobs:
  build-and-deploy-doc:
    name: Build documentation and deploy it to GH Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      ASSETS: assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Build documentation using Sphinx
        run: |
          docker run \
            --rm \
            -v ${PWD}:/project \
            -w /project \
            sphinxdoc/sphinx:latest \
            sphinx-build docs/source ${{ env.ASSETS }}/
      - name: Setup GitHub Pages
        uses: actions/configure-pages@main
      - name: Upload HTML
        uses: actions/upload-pages-artifact@main
        with:
          path: ${{ env.ASSETS }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
